spring.application.name=Web-2026-i
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/universidadesdb
spring.datasource.username=user_software
spring.datasource.password=1234
server.port=8086
spring.jpa.properties.hibernate.jdbc.ob.non_contextual_creation= true
logging.level.org.hibernate = ERROR
