spring.application.name=Web-2026-i
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario_inversion_db
spring.datasource.username=user_software
spring.datasource.password=1234
server.port=8086
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.hibernate = ERROR
